Dannavyboat/Dannavyboat/Controllers/ActivityController.cs
using Dannavyboat.Views.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebEdge.BusinessLayer.Interface;

namespace Dannavyboat.Controllers
{
    public class ActivityController : Controller
    {
        #region Properties
        public IActivity _activity;
        #endregion

        #region Constructor
        public ActivityController (IActivity activity)
        {
            this._activity = activity;
        }

        #endregion

        #region Public Methods
        [HttpGet]
        public ActionResult Activities()
        {
            //get contents of activity from db
            var activityModel = new ActivityViewModel();
            //should populate main activity by id ? or have url name 

            activityModel.ActivitiesList = _activity.GetAllActivities();
            //also needs to select 3 random activities

            return View("Activities", activityModel);
        }

        [HttpGet]
        public ActionResult GetActivityById(int activityId)
        {
            //get contents of activity from db
            var activityModel = new ActivityViewModel();

            activityModel.Activity = _activity.GetActivityById(activityId);
            //also needs to select 3 random activities

            return View("Activities", activityModel);
        }
        #endregion

        #region Private Methods


        #endregion

    }
}

Dannavyboat/Dannavyboat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/foundationcss")


    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="contain-to-grid ">
            <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
                <ul class="title-area">
                    <li class="name">
                        <h1>
                            <a href="#"
                                Navy Boat
                            </a>
                        </h1>
                    </li>
                    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
                </ul>
                <section class="top-bar-section">
                    <ul class="right">
                        <li class="divider"></li>
                        <li>@Html.ActionLink("Activities", "Activities", "Activity")</li>
                        <li class="divider"></li>
                        <li><a href="#">About Dan the Skipper</a></li>
                        <li class="divider"></li>
                        <li><a href="#">About the island</a></li>

                    </ul>
                </section>
            </nav>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - Web Edge Digital</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/foundation")
    @Scripts.Render("~/bundles/webedge")
    @RenderSection("scripts", required: false)
</body>
</html>